<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PetBox.Client.Config" Version="0.1.0-ci.324" />
    <PackageReference Include="Seq.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="version.json" CopyToOutputDirectory="PreserveNewest" Condition="Exists('version.json')" />
  </ItemGroup>

</Project>
